/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blogs/elec/': RouteRecordInfo<
      '/blogs/elec/',
      '/blogs/elec',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blogs/git-submodules/': RouteRecordInfo<
      '/blogs/git-submodules/',
      '/blogs/git-submodules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blogs/JS-bit-operator/': RouteRecordInfo<
      '/blogs/JS-bit-operator/',
      '/blogs/JS-bit-operator',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blogs/montgomery-modular-multiplication/': RouteRecordInfo<
      '/blogs/montgomery-modular-multiplication/',
      '/blogs/montgomery-modular-multiplication',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blogs/WSL2-gui-hi-dpi/': RouteRecordInfo<
      '/blogs/WSL2-gui-hi-dpi/',
      '/blogs/WSL2-gui-hi-dpi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/diaries/2022/10': RouteRecordInfo<
      '/diaries/2022/10',
      '/diaries/2022/10',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/diaries/2022/11': RouteRecordInfo<
      '/diaries/2022/11',
      '/diaries/2022/11',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/diaries/2023/10': RouteRecordInfo<
      '/diaries/2023/10',
      '/diaries/2023/10',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/diaries/2023/12': RouteRecordInfo<
      '/diaries/2023/12',
      '/diaries/2023/12',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/diaries/2024/01': RouteRecordInfo<
      '/diaries/2024/01',
      '/diaries/2024/01',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/meaningless': RouteRecordInfo<
      '/meaningless',
      '/meaningless',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/about.md': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/pages/blogs/elec/index.md': {
      routes:
        | '/blogs/elec/'
      views:
        | never
    }
    'src/pages/blogs/git-submodules/index.md': {
      routes:
        | '/blogs/git-submodules/'
      views:
        | never
    }
    'src/pages/blogs/JS-bit-operator/index.md': {
      routes:
        | '/blogs/JS-bit-operator/'
      views:
        | never
    }
    'src/pages/blogs/montgomery-modular-multiplication/index.md': {
      routes:
        | '/blogs/montgomery-modular-multiplication/'
      views:
        | never
    }
    'src/pages/blogs/WSL2-gui-hi-dpi/index.md': {
      routes:
        | '/blogs/WSL2-gui-hi-dpi/'
      views:
        | never
    }
    'src/pages/diaries/2022/10.md': {
      routes:
        | '/diaries/2022/10'
      views:
        | never
    }
    'src/pages/diaries/2022/11.md': {
      routes:
        | '/diaries/2022/11'
      views:
        | never
    }
    'src/pages/diaries/2023/10.md': {
      routes:
        | '/diaries/2023/10'
      views:
        | never
    }
    'src/pages/diaries/2023/12.md': {
      routes:
        | '/diaries/2023/12'
      views:
        | never
    }
    'src/pages/diaries/2024/01.md': {
      routes:
        | '/diaries/2024/01'
      views:
        | never
    }
    'src/pages/meaningless.vue': {
      routes:
        | '/meaningless'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
