/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/blogs/elec/': RouteRecordInfo<'/blogs/elec/', '/blogs/elec', Record<never, never>, Record<never, never>>,
    '/blogs/git-submodules/': RouteRecordInfo<'/blogs/git-submodules/', '/blogs/git-submodules', Record<never, never>, Record<never, never>>,
    '/blogs/JS-bit-operator/': RouteRecordInfo<'/blogs/JS-bit-operator/', '/blogs/JS-bit-operator', Record<never, never>, Record<never, never>>,
    '/blogs/montgomery-modular-multiplication/': RouteRecordInfo<'/blogs/montgomery-modular-multiplication/', '/blogs/montgomery-modular-multiplication', Record<never, never>, Record<never, never>>,
    '/blogs/WSL2-gui-hi-dpi/': RouteRecordInfo<'/blogs/WSL2-gui-hi-dpi/', '/blogs/WSL2-gui-hi-dpi', Record<never, never>, Record<never, never>>,
    '/diaries/2022/10': RouteRecordInfo<'/diaries/2022/10', '/diaries/2022/10', Record<never, never>, Record<never, never>>,
    '/diaries/2022/11': RouteRecordInfo<'/diaries/2022/11', '/diaries/2022/11', Record<never, never>, Record<never, never>>,
    '/diaries/2023/10': RouteRecordInfo<'/diaries/2023/10', '/diaries/2023/10', Record<never, never>, Record<never, never>>,
    '/diaries/2023/12': RouteRecordInfo<'/diaries/2023/12', '/diaries/2023/12', Record<never, never>, Record<never, never>>,
    '/diaries/2024/01': RouteRecordInfo<'/diaries/2024/01', '/diaries/2024/01', Record<never, never>, Record<never, never>>,
    '/meaningless': RouteRecordInfo<'/meaningless', '/meaningless', Record<never, never>, Record<never, never>>,
  }
}
