name: deploy
on: push
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      - run: |
          pnpm config set auto-install-peers true
          pnpm install
          pnpm build
          echo "build finish"
          cd dist
          git init
          echo "git repo inited"
          git config --local user.name  "Github Action"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git remote add origin "https://${{ secrets.GH_TOKEN }}@github.com/Discreater/Discreater.github.io.git"
          echo "remote added"
          git checkout -b gh-pages
          git add -A
          git commit -m 'deploy'
          echo "committed"
          git push -f --set-upstream origin gh-pages
          cd ..