name: deploy
on: 
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Set up pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: |
          pnpm install
          pnpm build
          echo "build finish"
          cd dist
          git init
          echo "git repo inited"
          git config --local user.name  "Github Action"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git remote add origin "https://${{ secrets.GH_TOKEN }}@github.com/Discreater/Discreater.github.io.git"
          echo "remote added"
          git checkout -b gh-pages
          git add -A
          git commit -m 'deploy'
          echo "committed"
          git push -f --set-upstream origin gh-pages
          cd ..