name: deploy
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      - run: |
          pnpm install --frozen-lockfile
          pnpm build
          cd dist
          git init
          git config user.name ${{ secrets.GH_USER }}
          git config user.email "${{ secrets.GH_MAIL }}"
          git remote add origin "https://${{ secrets.GH_TOKEN }}@github.com/Discreater/Discreater.github.io.git"
          git checkout -b gh-pages
          git add -A
          git commit -m 'deploy'
          git push -f 
          cd ..